### ISSUE TITLE
auto disconnect

### ISSUE THREAD

**Issue by AbadyElad** [Skoice/skoice#40] opened 2022-09-03 08:15 UTC
i want if player is not link he would be kick in 1m and he would be freeze

**Comment by AbadyElad** [comment] 2022-09-03 08:15
gae

**Comment by Matt2021-A** [comment] 2022-09-03 18:25
This is a duplicate of #39 and not well formed. Recommend closing this issue as non-actionable.

**Closed** 2022-09-03 18:43 UTC
Labels: duplicate
